image_path: '/home/jeet/scratch/data/img/coco/' #followed by train2014/
ann_root_files: ['/home/jeet/scratch/data/img/coco/annotations/vqa_val.json'] #, TODO: add it back '????????/train_split_vqa_val.json']

eval_image_path: '/home/jeet/scratch/data/img/coco/' #followed by train2014/
eval_ann_root_files: ['/home/jeet/scratch/data/img/coco/annotations/vqa_val.json']

# vg val set as OOD
ood_eval_image_path: '/home/jeet/scratch/data/img/vg/' #followed by train2014/
ood_eval_ann_root_files: ['/home/jeet/scratch/data/img/coco/annotations/vqa_val.json'] # TODO: change it

# set pretrained as a file path or an url
pretrained: '/home/jeet/scratch/models/blip/auth_ckpt/model_base.pth'

# size of vit model; base or large
vit: 'base'
batch_size_train: 256
batch_size_per_gpu: 8
batch_size_test: 32 

vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 2e-5

image_size: 480

k_test: 128
inference: 'rank'

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10